"""add task asset indexes

Revision ID: a76191c02132
Revises: 301b0fd2d7f8
Create Date: 2025-11-07 23:42:57.473180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76191c02132'
down_revision = '301b0fd2d7f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_asset_user_name', 'asset', ['user_id', 'name'], unique=False)
    op.create_index('ix_asset_user_type', 'asset', ['user_id', 'type'], unique=False)
    op.create_index('ix_task_user_asset', 'task', ['user_id', 'asset_id'], unique=False)
    op.create_index('ix_task_user_status_due', 'task', ['user_id', 'status', 'due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_user_status_due', table_name='task')
    op.drop_index('ix_task_user_asset', table_name='task')
    op.drop_index('ix_asset_user_type', table_name='asset')
    op.drop_index('ix_asset_user_name', table_name='asset')
    # ### end Alembic commands ###
