"""add attachments

Revision ID: f82a3a3b764f
Revises: a76191c02132
Create Date: 2025-11-07 23:49:42.679835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f82a3a3b764f'
down_revision = 'a76191c02132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('mime', sa.String(length=80), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_attachment_asset_id'), 'attachment', ['asset_id'], unique=False)
    op.create_index(op.f('ix_attachment_task_id'), 'attachment', ['task_id'], unique=False)
    op.create_index(op.f('ix_attachment_user_id'), 'attachment', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachment_user_id'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_task_id'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_asset_id'), table_name='attachment')
    op.drop_table('attachment')
    # ### end Alembic commands ###
